# Generated by Django 2.1.4 on 2018-12-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181229_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='guest', max_length=20),
        ),
    ]
