# Generated by Django 2.1.4 on 2018-12-29 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20181229_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessKey',
            fields=[
                ('token', models.CharField(max_length=64, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
