# Generated by Django 2.1.4 on 2018-12-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181229_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesskey',
            name='token',
            field=models.CharField(default='', max_length=64),
        ),
    ]
