# Generated by Django 2.1.4 on 2018-12-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestdata',
            old_name='athorized',
            new_name='authorized',
        ),
        migrations.AlterField(
            model_name='requestdata',
            name='time',
            field=models.IntegerField(default=1546194938.905364),
        ),
    ]
