# Generated by Django 2.1.4 on 2018-12-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_auto_20181230_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdata',
            name='time',
            field=models.IntegerField(),
        ),
    ]
