# Generated by Django 2.1.4 on 2018-12-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_auto_20181230_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannedip',
            name='time_banned',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
